services:
  website:
    container_name: "website"
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt/live/max-schluer.de-0001/fullchain.pem:/etc/nginx/certs/cert.pem"
      - "/etc/letsencrypt/live/max-schluer.de-0001/privkey.pem:/etc/nginx/certs/privkey.pem"
      - "./ssl-challenge/:/etc/nginx/html/"
    restart: unless-stopped
    